### ISSUE TITLE
Update to use newer node path code

### ISSUE THREAD

**Issue by nrkn** [browserify/path-browserify#11]
The version of path this uses is very old - many things won't work, eg my code uses path.posix because it needs to process posix paths even when running on windows, but it's missing in this version so you get undefined error in browser. Also path.parse and etc

I'd be happy to do a PR but only if it's welcome and likely to actually get merged - hasn't been any activity here in four years

Alternately is there a way to override core things like path in browserify? I read the manual etc but couldn't find anything. May have missed it.

**Comment by goto-bus-stop** [comment]
#12 updated to Node 8. i'll release soon after porting some more tests.

> Alternately is there a way to override core things like path in browserify? I read the manual etc but couldn't find anything. May have missed it.

you can use the `--require` flag with an alias to do this sort of thing:

```
browserify --require ./my-path-polyfill:path
```
