### ISSUE TITLE
How can I use typescript types with this module?

### ISSUE THREAD

**Issue by benwinding** [browserify/path-browserify#18]
Hi,

I'm aware this is an implementation of the node `path` module, but how can we use _this_ module with typescript types?

Cheers,
Ben

**Comment by manniniandrea** [comment]
import * as pathUtils from 'path-browserify';

pathUtils.join('path','filename');

**Comment by manniniandrea** [comment]
import * as pathUtils from 'path-browserify';

pathUtils.join('path1', 'filename');

**Comment by goto-bus-stop** [comment]
You mean like doing `import path from 'path-browserify'`? You probably have to add a typings file to your project and do something like
```ts
// path-browserify.d.ts
declare module 'path-browserify' {
  export * from 'path';
}
```
(Not super familiar with TypeScript so I can't guarantee that that'll work)

**Comment by benwinding** [comment]
Thanks for getting me on the right track!

I found out you can use types like this:
``` javascript
// types.d.ts
declare module 'path-browserify' {
  import path from 'path'
  export default path
}

// usage
import path from 'path-browserify'
path.join(...)
```

Types are working!
