### ISSUE TITLE
Won’t work in browser because of process.cwd()?

### ISSUE THREAD

**Issue by stucox** [browserify/path-browserify#8]
Admittedly I’m not using this through Browserify so not sure if that would make a difference, but this lib calls `process.cwd()` which isn’t available in browsers (`process` isn’t at all).

I wonder if it could be adapted to not use this — or at least use a default / accept a config option (empty string?) when `process.cwd()` isn’t available — and hence be more portable.

**Comment by seebigs** [comment]
same issue here

**Comment by xXACCEXx** [comment]
Perhaps a good default `process.cwd()` value could be `location.pathname`?

Or for modules, `import.meta.url`?

**Comment by dobromyslov** [comment]
process.cwd() is still used in the code https://github.com/browserify/path-browserify/blob/872fec31a8bac7b9b43be0e54ef3037e0202c5fb/index.js#L124

**Comment by goto-bus-stop** [comment]
You need a commonjs bundler to use this package, and the expectation is that the bundler can provide the `process` module. Browserify does that by default and in webpack I think there's a ProvidePlugin that you can configure with `process: 'process'`.

**Comment by avincentme** [comment]
You NEED to use path-browserify with a bundler like webpack or browserify.

With webpack version 5 onwards, webpack does not provide Node polyfills. Therefore you need to add a ProvidePlugin for process. ProvidePlugin essentially requires / imports a specific module for every js file that is resolved from your webpack entry.

**Install process polyfill:**
`npm i process
`

**Add the plugin to your webpack config**
```
    plugins: [
        new webpack.ProvidePlugin({
            process: 'process/browser',
        })
    ],
```

**Comment by stucox** [comment]
Given the above, I think that's all fair enough and this issue is just taking up space remaining open 😁

FWIW I'd love to see the JS community moving more towards portable JS where possible, rather than relying on users having specific tools in their build chain, but it's not remotely reasonable to demand that from a package which _literally has the name of a bundler in its name!_
